defaults:
- data: zarr
- dataloader: native_grid
- diagnostics: evaluation
- system: example
- graph: multi_scale
- model: graphtransformer
- training: default
- _self_

config_validation: True

data:
  frequency: 1h
  resolution: o96

  diagnostics: [] # Default behaviour is to interpolate between observed fields, not predict unseen fields

#dataloader:
# model_run_info: #Add for non-analysis training
#  start: 2020-02-05T12:00:00
#  length: 18 #in number of dates (* frequency for actual time)

model:
  model:
    _target_: anemoi.models.models.AnemoiModelEncProcDecMultiOutInterpolator
    latent_skip: False # True/False for skip connection on latent mesh
  residual:
    _target_: anemoi.models.layers.residual.SkipConnection
    step: 0 # use the previous step as skip connection

training:
  model_task: anemoi.training.train.tasks.GraphMultiOutInterpolator
  # Instead of inferred using multistep and timeincrement, specify time indices explicitly
  explicit_times:
    input: [0, 6]
    target: [1, 2, 3, 4, 5]
  multistep_input: 1
  multistep_output: 5

  rollout: null # override the default, it does not make sense for an interpolator
